/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nadrascalculator;

/**
 *
 * @author nadra
 */
public class JFrame extends javax.swing.JFrame {

    String total;
    double num1;
    double num2;
    String operator;
    double result;
    
    /**
     * Creates new form NewJFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        one_btn = new javax.swing.JButton();
        input_text = new javax.swing.JTextField();
        two_btn = new javax.swing.JButton();
        three_btn = new javax.swing.JButton();
        pluse_btn = new javax.swing.JButton();
        sub_btn = new javax.swing.JButton();
        div_btn = new javax.swing.JButton();
        multi_btn = new javax.swing.JButton();
        equal_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        four_btn = new javax.swing.JButton();
        five_btn = new javax.swing.JButton();
        six_btn = new javax.swing.JButton();
        seven_btn = new javax.swing.JButton();
        eight_btn = new javax.swing.JButton();
        nine_btn = new javax.swing.JButton();
        zerro_btn = new javax.swing.JButton();
        point_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        sqr_btn = new javax.swing.JButton();
        power_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sub_btn1 = new javax.swing.JButton();
        sub_btn2 = new javax.swing.JButton();
        sub_btn3 = new javax.swing.JButton();
        sub_btn4 = new javax.swing.JButton();
        sub_btn5 = new javax.swing.JButton();
        sub_btn6 = new javax.swing.JButton();
        sub_btn7 = new javax.swing.JButton();
        sub_btn8 = new javax.swing.JButton();
        sub_btn9 = new javax.swing.JButton();
        sub_btn10 = new javax.swing.JButton();
        sub_btn11 = new javax.swing.JButton();
        sub_btn12 = new javax.swing.JButton();
        sub_btn13 = new javax.swing.JButton();
        sub_btn14 = new javax.swing.JButton();
        sub_btn15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        one_btn.setText("1");
        one_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_btnActionPerformed(evt);
            }
        });

        two_btn.setText("2");
        two_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                two_btnActionPerformed(evt);
            }
        });

        three_btn.setText("3");
        three_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                three_btnActionPerformed(evt);
            }
        });

        pluse_btn.setText("+");
        pluse_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pluse_btnActionPerformed(evt);
            }
        });

        sub_btn.setText("-");
        sub_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btnActionPerformed(evt);
            }
        });

        div_btn.setText("/");
        div_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                div_btnActionPerformed(evt);
            }
        });

        multi_btn.setText("*");
        multi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multi_btnActionPerformed(evt);
            }
        });

        equal_btn.setText("=");
        equal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equal_btnActionPerformed(evt);
            }
        });

        back_btn.setText("<");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        four_btn.setText("4");
        four_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                four_btnActionPerformed(evt);
            }
        });

        five_btn.setText("5");
        five_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                five_btnActionPerformed(evt);
            }
        });

        six_btn.setText("6");
        six_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                six_btnActionPerformed(evt);
            }
        });

        seven_btn.setText("7");
        seven_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seven_btnActionPerformed(evt);
            }
        });

        eight_btn.setText("8");
        eight_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eight_btnActionPerformed(evt);
            }
        });

        nine_btn.setText("9");
        nine_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nine_btnActionPerformed(evt);
            }
        });

        zerro_btn.setText("0");
        zerro_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerro_btnActionPerformed(evt);
            }
        });

        point_btn.setText(",");
        point_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point_btnActionPerformed(evt);
            }
        });

        clear_btn.setText("CE");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        sqr_btn.setText("Sqr");
        sqr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqr_btnActionPerformed(evt);
            }
        });

        power_btn.setText("X^Y");
        power_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                power_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("Nadera_calculator ");

        sub_btn1.setText("%");
        sub_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn1ActionPerformed(evt);
            }
        });

        sub_btn2.setText("cos");
        sub_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn2ActionPerformed(evt);
            }
        });

        sub_btn3.setText("sin");
        sub_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn3ActionPerformed(evt);
            }
        });

        sub_btn4.setText("tan");
        sub_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn4ActionPerformed(evt);
            }
        });

        sub_btn5.setText("log");
        sub_btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn5ActionPerformed(evt);
            }
        });

        sub_btn6.setText("e^x");
        sub_btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn6ActionPerformed(evt);
            }
        });

        sub_btn7.setText("sinh");
        sub_btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn7ActionPerformed(evt);
            }
        });

        sub_btn8.setText("cosh");
        sub_btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn8ActionPerformed(evt);
            }
        });

        sub_btn9.setText("tanh");
        sub_btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn9ActionPerformed(evt);
            }
        });

        sub_btn10.setText("1/x");
        sub_btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn10ActionPerformed(evt);
            }
        });

        sub_btn11.setText("x^y");
        sub_btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn11ActionPerformed(evt);
            }
        });

        sub_btn12.setText("x^3");
        sub_btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn12ActionPerformed(evt);
            }
        });

        sub_btn13.setText("x^2");
        sub_btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn13ActionPerformed(evt);
            }
        });

        sub_btn14.setText("n!");
        sub_btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn14ActionPerformed(evt);
            }
        });

        sub_btn15.setText("+/-");
        sub_btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btn15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_text, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(one_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(two_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(three_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pluse_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sub_btn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(four_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(five_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(six_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(div_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(multi_btn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(seven_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(eight_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nine_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(zerro_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sub_btn1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sub_btn3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(sub_btn4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sub_btn2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(point_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sub_btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sqr_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sub_btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equal_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sub_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sub_btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sub_btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sub_btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sub_btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sub_btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sub_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(power_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sub_btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sub_btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(input_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(one_btn)
                    .addComponent(two_btn)
                    .addComponent(three_btn)
                    .addComponent(pluse_btn)
                    .addComponent(sub_btn)
                    .addComponent(sub_btn3)
                    .addComponent(sub_btn7)
                    .addComponent(sub_btn11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(four_btn)
                    .addComponent(five_btn)
                    .addComponent(six_btn)
                    .addComponent(div_btn)
                    .addComponent(multi_btn)
                    .addComponent(sub_btn2)
                    .addComponent(sub_btn8)
                    .addComponent(sub_btn13))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seven_btn)
                            .addComponent(eight_btn)
                            .addComponent(nine_btn)
                            .addComponent(sub_btn4)
                            .addComponent(sub_btn9)
                            .addComponent(sub_btn12)
                            .addComponent(zerro_btn)
                            .addComponent(sub_btn1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sqr_btn)
                            .addComponent(sub_btn5)
                            .addComponent(back_btn)
                            .addComponent(power_btn)
                            .addComponent(point_btn)
                            .addComponent(sub_btn15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(equal_btn)
                        .addComponent(sub_btn14))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clear_btn)
                        .addComponent(sub_btn10)
                        .addComponent(sub_btn6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void one_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_btnActionPerformed
        // TODO add your handling code here:

        total= input_text.getText() ; 
        input_text.setText(total+"1");

        
    }//GEN-LAST:event_one_btnActionPerformed

    private void two_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_two_btnActionPerformed
           // TODO add your handling code here:

          total= input_text.getText() ; 
          input_text.setText(total+"2");
           
    }//GEN-LAST:event_two_btnActionPerformed

    private void pluse_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pluse_btnActionPerformed
        try {
            operator="+";
            num1=Double.parseDouble(input_text.getText());
            input_text.setText("");
        }
        catch(Exception e) {
            System.out.print(e);
        }

        
    }//GEN-LAST:event_pluse_btnActionPerformed

    private void equal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equal_btnActionPerformed
         
        num2=Double.parseDouble(input_text.getText());
        if(operator=="+")
        {
            result=num1+num2;
            
            //answer=String.format("%.2f",result + "");
            input_text.setText(result + "");  
        }
        else if(operator=="-")
        {
            result=num1-num2;
            //answer=String.format("%.2f",result);
            input_text.setText(result + "");  
        }
        else if(operator=="/")
        {
            result=num1/num2;
            //answer=String.format("%.2f",result);
            input_text.setText(result + "");  
        }
        else if (operator=="*")
        {
            result=num1*num2;
            //answer=String.format("%.2f",result);
            input_text.setText(result + "");  
        }
        else if (operator=="%"){
            
            result=num1%num2;
            //answer=Srting.format("%.2f",result);
            input_text.setText(result + "");    
        }
        else if (operator=="X^Y")
        {
            double resultt=1;
            for(int i=0;i<num2;i++)
            {
            resultt=num1*resultt;
            
            }
            //answer=Srting.format("%.2f",resultt);
            input_text.setText(resultt + "");    
        }
       
       
    }//GEN-LAST:event_equal_btnActionPerformed

    private void four_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_four_btnActionPerformed
        // TODO add your handling code here:
        total= input_text.getText() ; 
        input_text.setText(total+"4");
    }//GEN-LAST:event_four_btnActionPerformed

    private void five_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_five_btnActionPerformed
        // TODO add your handling code here:

        total= input_text.getText() ; 
        input_text.setText(total+"5");
    }//GEN-LAST:event_five_btnActionPerformed

    private void seven_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seven_btnActionPerformed
         // TODO add your handling code here:

         total= input_text.getText() ; 
        input_text.setText(total+"7");
    }//GEN-LAST:event_seven_btnActionPerformed

    private void eight_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eight_btnActionPerformed
         // TODO add your handling code here:
 
         total= input_text.getText() ; 
        input_text.setText(total+"8");
    }//GEN-LAST:event_eight_btnActionPerformed

    private void zerro_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerro_btnActionPerformed
         // TODO add your handling code here:
         total= input_text.getText() ; 
        input_text.setText(total+"0");
    }//GEN-LAST:event_zerro_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
              // TODO add your handling code here:
              input_text.setText("");
              result=0;
              num1=(0);
              num2=(0);

    }//GEN-LAST:event_clear_btnActionPerformed

    private void sqr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqr_btnActionPerformed
        // TODO add your handling code here:
        Double a=Math.sqrt(Double.parseDouble(input_text.getText()));
        input_text.setText("");
        input_text.setText(input_text.getText()+a);
    }//GEN-LAST:event_sqr_btnActionPerformed

    private void power_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_power_btnActionPerformed
        // TODO add your handling code here:
         try {
            operator="X^Y";
            num1=Double.parseDouble(input_text.getText());
            input_text.setText("");
        }
        catch(Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_power_btnActionPerformed

    private void sub_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btnActionPerformed
       // TODO add your handling code here:
        try {
            operator="-";
            num1=Double.parseDouble(input_text.getText());
            input_text.setText("");
        }
        catch(Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_sub_btnActionPerformed

    private void three_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_three_btnActionPerformed
         // TODO add your handling code here:

         total= input_text.getText() ; 
        input_text.setText(total+"3");
    }//GEN-LAST:event_three_btnActionPerformed

    private void six_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_six_btnActionPerformed
         // TODO add your handling code here:

        total= input_text.getText() ; 
        input_text.setText(total+"6");
    }//GEN-LAST:event_six_btnActionPerformed

    private void nine_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nine_btnActionPerformed
        // TODO add your handling code here:

        total= input_text.getText() ; 
        input_text.setText(total+"9");
    }//GEN-LAST:event_nine_btnActionPerformed

    private void div_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_div_btnActionPerformed
        // TODO add your handling code here:
         try {
            operator="/";
            num1=Double.parseDouble(input_text.getText());
            input_text.setText("");
        }
        catch(Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_div_btnActionPerformed

    private void multi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multi_btnActionPerformed
      // TODO add your handling code here:
       try {
            operator="*";
            num1=Double.parseDouble(input_text.getText());
            input_text.setText("");
        }
        catch(Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_multi_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        int length=input_text.getText().length();
        int number=input_text.getText().length()-1;
        String store;
        
        if(length >0)
        {
            StringBuilder back=new StringBuilder(input_text.getText());
            back.deleteCharAt(number);
            store=back.toString();
            input_text.setText(store);
        }
        
    }//GEN-LAST:event_back_btnActionPerformed

    private void sub_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn1ActionPerformed
        // TODO add your handling code here:
         try {
            operator="%";
            num1=Double.parseDouble(input_text.getText());
            input_text.setText("");
        }
        catch(Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_sub_btn1ActionPerformed

    private void sub_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn2ActionPerformed
        // TODO add your handling code here:
        Double a=Math.cos(Double.parseDouble(input_text.getText()));
        input_text.setText("");
        input_text.setText(input_text.getText()+a);
    }//GEN-LAST:event_sub_btn2ActionPerformed

    private void sub_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn3ActionPerformed
        // TODO add your handling code here:
        Double a=Math.sin(Double.parseDouble(input_text.getText()));
        input_text.setText("");
        input_text.setText(input_text.getText()+a);
    }//GEN-LAST:event_sub_btn3ActionPerformed

    private void sub_btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn4ActionPerformed
        // TODO add your handling code here:
        Double a=Math.tan(Double.parseDouble(input_text.getText()));
        input_text.setText("");
        input_text.setText(input_text.getText()+a);
    }//GEN-LAST:event_sub_btn4ActionPerformed

    private void sub_btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn5ActionPerformed
        // TODO add your handling code here:
        Double a=Math.log(Double.parseDouble(input_text.getText()));
        input_text.setText("");
        input_text.setText(input_text.getText()+a);
    }//GEN-LAST:event_sub_btn5ActionPerformed

    private void sub_btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn6ActionPerformed
        // TODO add your handling code here:
        Double a=Math.exp(Double.parseDouble(input_text.getText()));
        input_text.setText("");
        input_text.setText(input_text.getText()+a);
    }//GEN-LAST:event_sub_btn6ActionPerformed

    private void sub_btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn7ActionPerformed
        // TODO add your handling code here:
        Double a=Math.sinh(Double.parseDouble(input_text.getText()));
        input_text.setText("");
        input_text.setText(input_text.getText()+a);
    }//GEN-LAST:event_sub_btn7ActionPerformed

    private void sub_btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn8ActionPerformed
        // TODO add your handling code here:
        Double a=Math.cosh(Double.parseDouble(input_text.getText()));
        input_text.setText("");
        input_text.setText(input_text.getText()+a);
    }//GEN-LAST:event_sub_btn8ActionPerformed

    private void sub_btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn9ActionPerformed
        // TODO add your handling code here:
        Double a=Math.tanh(Double.parseDouble(input_text.getText()));
        input_text.setText("");
        input_text.setText(input_text.getText()+a);
    }//GEN-LAST:event_sub_btn9ActionPerformed

    private void sub_btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn10ActionPerformed
        // TODO add your handling code here:
        Double a=1/(Double.parseDouble(input_text.getText()));
        input_text.setText("");
        input_text.setText(input_text.getText()+a);
    }//GEN-LAST:event_sub_btn10ActionPerformed

    private void sub_btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_btn11ActionPerformed

    private void sub_btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn12ActionPerformed
        // TODO add your handling code here:
          Double a=(Double.parseDouble(input_text.getText()));
        a=a*a*a;
        input_text.setText("");
        input_text.setText(input_text.getText()+a);
    }//GEN-LAST:event_sub_btn12ActionPerformed

    private void sub_btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn13ActionPerformed
        // TODO add your handling code here:
        Double a=(Double.parseDouble(input_text.getText()));
        a=a*a;
        input_text.setText("");
        input_text.setText(input_text.getText()+a);
    }//GEN-LAST:event_sub_btn13ActionPerformed

    private void sub_btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn14ActionPerformed
        // TODO add your handling code here:
        Double a=Double.parseDouble(input_text.getText());
        double fact=1;
        while(a!=0)
        {
            fact=fact*a;
            a--;
        }
        input_text.setText("");
        input_text.setText(input_text.getText()+fact);
        
    }//GEN-LAST:event_sub_btn14ActionPerformed

    private void sub_btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btn15ActionPerformed
        // TODO add your handling code here:
        Double a=Double.parseDouble(String.valueOf(input_text.getText()));
        a=a*(-1);
        input_text.setText(String.valueOf(a));
   
        
    }//GEN-LAST:event_sub_btn15ActionPerformed

    private void point_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point_btnActionPerformed
        // TODO add your handling code here:
        total= input_text.getText() ;
        if (!input_text.getText().contains("."))
            input_text.setText(total+".");            
      
    }//GEN-LAST:event_point_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton div_btn;
    private javax.swing.JButton eight_btn;
    private javax.swing.JButton equal_btn;
    private javax.swing.JButton five_btn;
    private javax.swing.JButton four_btn;
    private javax.swing.JTextField input_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton multi_btn;
    private javax.swing.JButton nine_btn;
    private javax.swing.JButton one_btn;
    private javax.swing.JButton pluse_btn;
    private javax.swing.JButton point_btn;
    private javax.swing.JButton power_btn;
    private javax.swing.JButton seven_btn;
    private javax.swing.JButton six_btn;
    private javax.swing.JButton sqr_btn;
    private javax.swing.JButton sub_btn;
    private javax.swing.JButton sub_btn1;
    private javax.swing.JButton sub_btn10;
    private javax.swing.JButton sub_btn11;
    private javax.swing.JButton sub_btn12;
    private javax.swing.JButton sub_btn13;
    private javax.swing.JButton sub_btn14;
    private javax.swing.JButton sub_btn15;
    private javax.swing.JButton sub_btn2;
    private javax.swing.JButton sub_btn3;
    private javax.swing.JButton sub_btn4;
    private javax.swing.JButton sub_btn5;
    private javax.swing.JButton sub_btn6;
    private javax.swing.JButton sub_btn7;
    private javax.swing.JButton sub_btn8;
    private javax.swing.JButton sub_btn9;
    private javax.swing.JButton three_btn;
    private javax.swing.JButton two_btn;
    private javax.swing.JButton zerro_btn;
    // End of variables declaration//GEN-END:variables
}
